[genesis.head]
icon = "https://avatars.githubusercontent.com/u/168826426"

[genesis.header.nav.logo]
src = "/assets/img/pagine.svg"
height = 50

# Header

[[genesis.header.nav.items]]
name = "Documentation"
link = "/docs/"

[[genesis.header.nav.items]]
name = "Repositories"
link = "https://github.com/webpagine"

# Footer

[genesis.footer.logo]
src = "/assets/img/symboltics_white.svg"
height = 40

[genesis.footer.copyright]
owner = "Symboltics"
date = "2024"
license = "Text is available under the Creative Commons Attribution-ShareAlike License 4.0; additional terms may apply."

[[genesis.footer.lists]]
title = "About Symboltics"
links = [
    { name = "Vision", link = "" },
    { name = "Mission", link = "" },
    { name = "Where we go", link = "" },
    { name = "Where we come", link = "" },
]

[[genesis.footer.lists]]
title = "Infrastructure"
links = [
    { name = "LangVM", link = "https://github.com/langvm/" },
    { name = "Symonarch", link = "https://github.com/symonarch/" },
    { name = "HyperArchy", link = "https://github.com/hyperarchy/" },
    { name = "Web Pagine", link = "https://github.com/webpagine/" },
]

[[genesis.footer.lists]]
title = "Services"
links = [
    { name = "Modularis", link = "https://github.com/symboltics/modularis/" },
]

[[genesis.footer.media.list]]
icon = "github"
link = "https://github.com/jellyterra"

[[genesis.footer.media.list]]
icon = "x"
link = "https://x.com/jellyterra"

