[[unit]]
template = "genesis:locale"
output = "/index.html"
define = { title = "Pagine - Web Generator" }

[[unit]]
template = "genesis:page"
output = "/404.html"
define = { title = "Pagine - Web Generator", content = "/404.html" }
