name: Deploy

on:
  push:
    branches:
      - master

permissions:
  contents: read
  pages: write
  id-token: write

concurrency:
  group: "pages"
  cancel-in-progress: false

defaults:
  run:
    shell: bash

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Install TypeScript Compiler
        run: sudo apt install node-typescript -y

      - name: Install Pagine
        run: go install github.com/webpagine/pagine/v2/cmd/pagine@v2.4.0

      - name: Checkout
        uses: actions/checkout@v4
        with:
          submodules: recursive
          fetch-depth: 0

      - name: Setup Pages
        id: pages
        uses: actions/configure-pages@v4

      - name: Build with Pagine
        run: ~/go/bin/pagine --public ../public/

      - name: Upload artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: ../public/

      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4